### ISSUE TITLE
Cant load saved profiles

### ISSUE THREAD

**Issue by pckotzer** [WSTxda/ViperFX-RE-Releases#25]
It it crashes when i try to load a profile.

123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869
time: 1727267659537
msg: android.system.ErrnoException: open failed: EACCES (Permission denied)
stacktrace: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	... 1 more
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.wstxda.viper4android/files/Preset/Basic Bluetooth underdog pack.xml: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at s5.b.g0(Unknown Source:71)
	at x1.e.b(Unknown Source:34)
	at com.wstxda.viper4android.MainActivity.s(Unknown Source:478)
	at m1.a.m(Unknown Source:4)
	at g5.c.f(Unknown Source:135)
	at j.o.e(Unknown Source:4)
	at j.o.q(Unknown Source:28)
	at j.x.onItemClick(Unknown Source:40)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1271)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3284)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4240)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:4003)
	at k.x1.onTouchEvent(Unknown Source:37)
	at android.view.View.performOnTouchCallback(View.java:16266)
	at android.view.View.dispatchTouchEvent(View.java:16223)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3119)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2792)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2806)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2569)
	at android.view.View.dispatchPointerEvent(View.java:16548)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7586)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7353)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6745)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6802)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6768)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6934)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6776)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6991)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6749)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6802)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6768)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6776)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6749)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9853)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9804)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9773)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9995)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:349)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	... 3 more
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8480)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 51 more
[GitHub](https://github.com/lus/pasty) | [Change privacy settings](https://paste.crdroid.net/eS7lgT#)

**Comment by WSTxda** [comment]
Apparently a problem with storage permission, I'll investigate, in the meantime try loading profiles in a directory outside of `Android/data`

**Comment by WSTxda** [comment]
@pckotzer check new version

**Comment by ionutgherman** [comment]
@WSTxda still an issue. Using 7.1 with 6.3 driver

**Comment by gi728h** [comment]
If you are facing problems while loading files in `Android/data` then I have a workaround

**Comment by yfl888** [comment]
The configuration file path of the sound effect v7.2 I am using now is /storage/emulated/0/Android/data/com.wstxda.viper4android/files/
